name: automatically-check-broken-links

on:
  push
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 8 * * 4'
# permissions:
#  contents: read
#  issues: write 
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      id: last_status
      # with:
      #   use-quiet-mode: 'no'
      #   use-verbose-mode: 'yes'
      #   check-modified-files-only: 'yes'

  create-issue:
    #&& steps.last_status.outputs.last_status == 'failure'
    if: ${{ always() }}
    needs: markdown-link-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 